include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Naming conventions
    file_names: true
    camel_case_types: true
    library_prefixes: true
    constant_identifier_names: true
    non_constant_identifier_names: false

    # Style & structure
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_const_literals_to_create_immutables: true
    always_put_control_body_on_new_line: true
    lines_longer_than_80_chars: false  # çünkü 100 karaktere kadar izin veriyoruz

    # Safety
    use_build_context_synchronously: true
    avoid_print: false  # README'de print yasaklanmamış, bu yüzden kapalı

    # Others
    sort_constructors_first: true
    unnecessary_this: true
    prefer_typing_uninitialized_variables: true